"""Add notes column to issuance

Revision ID: 666aa926b968
Revises: 7dbc359eea51
Create Date: 2025-12-29 19:29:52.079263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '666aa926b968'
down_revision: Union[str, Sequence[str], None] = '7dbc359eea51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuance', sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_reader_name'), table_name='reader')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reader_name'), 'reader', ['name'], unique=False)
    op.drop_column('issuance', 'notes')
    # ### end Alembic commands ###
